### ISSUE TITLE
Add search in government website list page

### ISSUE THREAD

**Issue by bsantosh909** [Know-Nepal/website#1]
## What

Since the list can be long and finding a specific government website can be hard, we will need to add a search bar in the goverment websites page

## How

The package fuse.js has been already added, need to implement search using this package.

> [!IMPORTANT]
> "threshold" should be set to 0.3
> "ignoreLocation" should be set to true

**Comment by susanhsrestha** [comment]
I'd like to work on this issue.

**Comment by thenishantsapkota** [comment]
Sure, assigning the issue to you @susanhsrestha
