### ISSUE TITLE
Add search in Tech companies list page

### ISSUE THREAD

**Issue by bsantosh909** [Know-Nepal/website#2]
## What

Since the list can be long and finding a specific tech company can be hard, we will need to add a search bar in the tech companies page.

## How

The package fuse.js has been already added, need to implement search using this package.

> [!IMPORTANT]
> "threshold" should be set to 0.3
> "ignoreLocation" should be set to true

**Comment by Rizina** [comment]
I would like to work on this issue

**Comment by bsantosh909** [comment]
> I would like to work on this issue

@Rizina Sure, assigning it to you.
